spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:mysql://localhost:3306/crm?useSSL=false
    username: root
    password: root
    
  cloud:
    stream:
      bindings:
        crmQueue:
          destination: customers
      default:
        contentType: application/json
        
#   security:
#     basic:
#       enabled: true
#     user:
#       name: melita_task
#       password: 12345
        
server:
  port: 9095
