
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
  jpa:
    hibernate:
      ddl-auto: validate
  
  datasource:
    url: jdbc:mysql://localhost:3306/crm?useSSL=false
    username: root
    password: root

  cloud:
    stream:
      bindings:
        crmQueue:
          destination: customers
          group: crm
      default:
        contentType: application/json
        
server:
  port: 9094
